### ISSUE TITLE
insert() returns bool, but is not used. 

### ISSUE THREAD

**Issue by lharikrishnan1993** [HarishKarunakaran/Data_Structures#2]
https://github.com/HarishKarunakaran/Data_Structures/blob/38f042982f547c3e9d309393bf63098dee06b3f7/src/kdtree/kdtree.cpp#L85

Why does insert() return bool if it is not used? How do you intend to use it?

**Comment by HarishKarunakaran** [comment]
Good catch! I designed it for calling insert by the user and I forgot about this interface I used..

Will this statement work instead,
for(auto& node_data : data)
{
if(!(insert(node_data))
{return false;}
return true;
}
